apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::469127932472:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::469127932472:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-3YBHWMN46PQS
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-11T20:03:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1185"
  uid: d6b2c641-3a8f-416d-aa74-d478ee12d2f8
